"""
ETSI GS QKD 014 Key Management Entity (KME) Server

Implements the ETSI GS QKD 014 REST API. Keys are generated by the BB84
simulator and held in two pools:

  _available  — keys generated but not yet issued to any SAE
  _pending    — keys issued to the master SAE, awaiting retrieval by slave SAE

This mirrors how a real dual-KME deployment works: Alice's KME and Bob's KME
each hold the same key material (synchronized via the quantum channel). Alice's
application fetches via enc_keys; Bob's application fetches the matching key by
key_ID via dec_keys.

Endpoints (ETSI GS QKD 014 §5):
  GET  /api/v1/keys/{slave_SAE_ID}/status
  GET  /api/v1/keys/{slave_SAE_ID}/enc_keys?number=N&size=S
  POST /api/v1/keys/{slave_SAE_ID}/enc_keys   (body: {"number": N, "size": S})
  POST /api/v1/keys/{slave_SAE_ID}/dec_keys   (body: {"key_IDs": [{"key_ID": "..."}]})

Usage:
  pip install flask
  python kme_server.py
  # API available at http://127.0.0.1:5000
"""

import logging
import threading
import uuid
import base64
from collections import deque
from dataclasses import dataclass

from flask import Flask, jsonify, request, abort

from bb84_simulator import BB84Protocol

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

app = Flask(__name__)

# ── Configuration ──────────────────────────────────────────────────────────────

KME_ID = "kme-sim-01"
PARTNER_KME_ID = "kme-sim-02"
DEFAULT_KEY_SIZE = 256       # bits
MIN_KEY_SIZE = 64            # bits
MAX_KEY_SIZE = 1024          # bits
MAX_KEYS_PER_REQUEST = 20
POOL_TARGET = 50             # keys to keep available
POOL_REFILL_TRIGGER = 10     # refill when available count drops below this


# ── Key storage ────────────────────────────────────────────────────────────────

@dataclass
class StoredKey:
    key_id: str
    key_bytes: bytes
    size_bits: int


class KeyPool:
    """
    Thread-safe key pool backed by BB84 simulation.

    Lifecycle:
      _available  → get_keys()    → _pending   (master SAE has been issued the key)
      _pending    → get_by_ids()  → returned   (slave SAE retrieves by key_ID)
    """

    def __init__(self) -> None:
        self._available: dict[str, StoredKey] = {}
        self._available_order: deque[str] = deque()
        self._pending: dict[str, StoredKey] = {}
        self._lock = threading.Lock()
        self._proto = BB84Protocol(error_rate=0.01)
        log.info("Initialising key pool (target: %d keys)...", POOL_TARGET)
        self._fill_to_target()
        log.info("Key pool ready: %d keys available", len(self._available))

    # ── Key generation ─────────────────────────────────────────────────────────

    def _generate(self, size_bits: int = DEFAULT_KEY_SIZE) -> StoredKey:
        """Run BB84 and return a key of the requested size."""
        # Send enough raw qubits to yield at least size_bits after sifting (~50%)
        n_raw = max(4096, size_bits * 25)
        result = self._proto.run(n_bits=n_raw)
        if not result.secure:
            raise RuntimeError("BB84 failed — QBER exceeded threshold")

        # Stretch or truncate to exact requested length
        needed = size_bits // 8
        key = result.final_key
        import hashlib
        while len(key) < needed:
            key += hashlib.blake2b(key, digest_size=32).digest()
        key = key[:needed]

        return StoredKey(
            key_id=str(uuid.uuid4()),
            key_bytes=key,
            size_bits=size_bits,
        )

    def _fill_to_target(self) -> None:
        while len(self._available) < POOL_TARGET:
            k = self._generate()
            self._available[k.key_id] = k
            self._available_order.append(k.key_id)

    def _maybe_refill(self) -> None:
        if len(self._available) < POOL_REFILL_TRIGGER:
            threading.Thread(target=self._fill_to_target, daemon=True).start()

    # ── Public API ─────────────────────────────────────────────────────────────

    def get_keys(self, count: int, size_bits: int = DEFAULT_KEY_SIZE) -> list[StoredKey]:
        """
        Issue `count` keys of `size_bits` to the master SAE.
        Keys move from _available to _pending (awaiting slave retrieval).
        """
        with self._lock:
            # Find available keys matching the requested size
            matching_ids = [
                kid for kid in self._available_order
                if self._available[kid].size_bits == size_bits
            ]

            # Generate extra keys on-demand if the pool doesn't have enough
            while len(matching_ids) < count:
                k = self._generate(size_bits)
                self._available[k.key_id] = k
                self._available_order.append(k.key_id)
                matching_ids.append(k.key_id)

            selected_ids = matching_ids[:count]
            keys: list[StoredKey] = []
            for kid in selected_ids:
                k = self._available.pop(kid)
                self._available_order.remove(kid)
                self._pending[kid] = k
                keys.append(k)

        self._maybe_refill()
        return keys

    def get_by_ids(self, key_ids: list[str]) -> list[StoredKey]:
        """
        Fetch specific keys by key_ID for the slave SAE.
        Keys are removed from _pending once retrieved.
        """
        with self._lock:
            found: list[StoredKey] = []
            for kid in key_ids:
                if kid in self._pending:
                    found.append(self._pending.pop(kid))
        return found

    @property
    def available_count(self) -> int:
        return len(self._available)


pool = KeyPool()


# ── Helpers ────────────────────────────────────────────────────────────────────

def key_to_dict(k: StoredKey) -> dict:
    return {
        "key_ID": k.key_id,
        "key": base64.b64encode(k.key_bytes).decode(),
    }


def _int_param(name: str, default: int, lo: int, hi: int) -> int:
    raw = request.args.get(name, str(default))
    try:
        val = int(raw)
    except ValueError:
        abort(400, description=f"'{name}' must be an integer")
    if not lo <= val <= hi:
        abort(400, description=f"'{name}' must be between {lo} and {hi}")
    return val


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.get("/api/v1/keys/<slave_sae_id>/status")
def route_status(slave_sae_id: str):
    """ETSI QKD 014 §5.2 — Status of available key material."""
    return jsonify({
        "source_KME_ID": KME_ID,
        "target_KME_ID": PARTNER_KME_ID,
        "master_SAE_ID": "sae-master",
        "slave_SAE_ID": slave_sae_id,
        "key_size": DEFAULT_KEY_SIZE,
        "stored_key_count": pool.available_count,
        "max_key_count": POOL_TARGET,
        "max_key_per_request": MAX_KEYS_PER_REQUEST,
        "max_key_size": MAX_KEY_SIZE,
        "min_key_size": MIN_KEY_SIZE,
        "max_SAE_ID_count": 0,
    })


@app.get("/api/v1/keys/<slave_sae_id>/enc_keys")
def route_enc_keys_get(slave_sae_id: str):
    """ETSI QKD 014 §5.3 — Issue keys to the master (encrypting) SAE."""
    number = _int_param("number", 1, 1, MAX_KEYS_PER_REQUEST)
    size   = _int_param("size", DEFAULT_KEY_SIZE, MIN_KEY_SIZE, MAX_KEY_SIZE)
    if size % 8 != 0:
        abort(400, description="Key size must be a multiple of 8 bits")
    keys = pool.get_keys(number, size)
    log.info("enc_keys  slave=%s  n=%d  size=%d", slave_sae_id, len(keys), size)
    return jsonify({"keys": [key_to_dict(k) for k in keys]})


@app.post("/api/v1/keys/<slave_sae_id>/enc_keys")
def route_enc_keys_post(slave_sae_id: str):
    """ETSI QKD 014 §5.3 — Issue keys to the master SAE (POST variant)."""
    body   = request.get_json(silent=True) or {}
    number = min(int(body.get("number", 1)), MAX_KEYS_PER_REQUEST)
    size   = int(body.get("size", DEFAULT_KEY_SIZE))
    if size % 8 != 0:
        abort(400, description="Key size must be a multiple of 8 bits")
    keys = pool.get_keys(number, size)
    log.info("enc_keys POST  slave=%s  n=%d  size=%d", slave_sae_id, len(keys), size)
    return jsonify({"keys": [key_to_dict(k) for k in keys]})


@app.post("/api/v1/keys/<slave_sae_id>/dec_keys")
def route_dec_keys(slave_sae_id: str):
    """ETSI QKD 014 §5.4 — Retrieve specific keys for the slave (decrypting) SAE."""
    body = request.get_json(silent=True) or {}
    raw_ids = body.get("key_IDs", [])
    if not raw_ids:
        abort(400, description="Request body must include 'key_IDs'")
    if len(raw_ids) > MAX_KEYS_PER_REQUEST:
        abort(400, description=f"Too many key IDs (max {MAX_KEYS_PER_REQUEST})")

    key_ids = [item.get("key_ID") for item in raw_ids if isinstance(item, dict) and "key_ID" in item]
    keys = pool.get_by_ids(key_ids)
    if not keys:
        abort(404, description="No matching keys found — key may not exist or already retrieved")
    log.info("dec_keys  slave=%s  requested=%d  found=%d", slave_sae_id, len(key_ids), len(keys))
    return jsonify({"keys": [key_to_dict(k) for k in keys]})


@app.errorhandler(400)
@app.errorhandler(404)
def handle_error(e):
    return jsonify({"message": str(e.description)}), e.code


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("ETSI GS QKD 014 KME Server (BB84-backed simulation)")
    print("=" * 55)
    print(f"  KME ID : {KME_ID}")
    print(f"  API    : http://127.0.0.1:5000/api/v1/keys/")
    print()
    print("  Example requests:")
    print("    curl http://127.0.0.1:5000/api/v1/keys/sae-bob/status")
    print("    curl http://127.0.0.1:5000/api/v1/keys/sae-bob/enc_keys")
    print()
    app.run(host="127.0.0.1", port=5000, debug=False)
